// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DescriptionPopup: typeof import('./src/components/DescriptionPopup.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IndexGraphic: typeof import('./src/components/IndexGraphic.vue')['default']
    ShareCardDefault: typeof import('./src/components/share-card/ShareCardDefault.vue')['default']
    ShareCardReceiptsD: typeof import('./src/components/share-card/ShareCardReceiptsD.vue')['default']
    ShareCardReceiptsL: typeof import('./src/components/share-card/ShareCardReceiptsL.vue')['default']
    ShareCardTE: typeof import('./src/components/share-card/ShareCardTE.vue')['default']
    SharePopup: typeof import('./src/components/share-card/SharePopup.vue')['default']
    StockPopup: typeof import('./src/components/StockPopup.vue')['default']
  }
}
